[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odooportalui
db_password = odooportalui
db_name = odooportalui
dbfilter = ^odooportalui$
list_db = False
admin_passwd = admin
